version: '3'
services:
  db:
    image: postgres:11.5
    ports:
      - 15432:5432
    volumes:
      - dbdata:/var/lib/postgresql/data
      - ./initdb.d:/docker-entrypoint-initdb.d/:ro
    environment:
      - POSTGRES_USER=${PGSQL_ROOT_USER}
      - POSTGRES_PASSWD=${PGSQL_ROOT_PASS}
      - APP_DATABASE_HOST=${APP_DATABASE_HOST}
      - APP_DATABASE_PORT=${APP_DATABASE_PORT}
      - APP_DATABASE_USER=${APP_DATABASE_USER}
      - APP_DATABASE_PASS=${APP_DATABASE_PASS}
      - APP_DATABASE_DBNAME=${APP_DATABASE_DBNAME}
      - APP_DATABASE_SCHEMA=${APP_DATABASE_SCHEMA}
  auth:
    image: gradle:5.5-jdk8
    working_dir: /app
    command: ./gradlew --no-daemon -p auth bootRun
    depends_on:
      - db
    ports:
      - 8000:8080
    volumes:
      - .:/app
    environment:
      - APP_DEBUG=true
      - APP_JWT_SECRET=${APP_JWT_SECRET}
      - APP_DATABASE_HOST=${APP_DATABASE_HOST}
      - APP_DATABASE_PORT=${APP_DATABASE_PORT}
      - APP_DATABASE_USER=${APP_DATABASE_USER}
      - APP_DATABASE_PASS=${APP_DATABASE_PASS}
      - APP_DATABASE_DBNAME=${APP_DATABASE_DBNAME}
      - APP_DATABASE_SCHEMA=${APP_DATABASE_SCHEMA}
  app:
    image: gradle:5.5-jdk8
    working_dir: /app
    command: ./gradlew --no-daemon -p app bootRun
    depends_on:
      - db
    ports:
      - 8001:8080
    volumes:
      - .:/app
    environment:
      - APP_DEBUG=true
      - APP_DATABASE_HOST=${APP_DATABASE_HOST}
      - APP_DATABASE_PORT=${APP_DATABASE_PORT}
      - APP_DATABASE_USER=${APP_DATABASE_USER}
      - APP_DATABASE_PASS=${APP_DATABASE_PASS}
      - APP_DATABASE_DBNAME=${APP_DATABASE_DBNAME}
      - APP_DATABASE_SCHEMA=${APP_DATABASE_SCHEMA}
volumes:
  dbdata:
    driver: local